### ISSUE TITLE
Definition of A_t

### ISSUE THREAD

**Issue by pjayathissa** [architecture-building-systems/RC_BuildingSimulator#1]
A_t is currently being defined by the formula for A_tot, the total internal surface area of the room. There appears to be a syntax error in the ISO 13790 standard, Section C.2 which links to Section 7.2.2.2

**Comment by wgayton** [comment]
Having worked with the team at NREL to implement ISO 13790 in java I can share that 
A_t or At is defined as being the area of all surfaces facing the room.

`
/**
 * At: the area of all surfaces facing the room, in m2;
 * Am: the effective mass area, in m2;
 * Af: the gross floor area
 * Cm: the internal heat capacity, determined according to 12.3.1, in J/K;
 * Rat: the dimensionless ratio between the internal surfaces area and the floor area, assumed to be equal to 4.5.
 *
 * Symbol  Quantity                                                     Unit
 *  ------- ----------------------------------------------------------- ---------------
 *  A 		area                                                        m²
 *  a 		numerical parameter in utilisation factor
 *  B 		correction factor for an unconditioned adjacent space
 *  C 		effective heat capacity of a conditioned space              J/K
 *  c 		specific heat capacity                                      J/(kg·K)
 *  d 		layer thickness                                             m
 *  F 		factor
 *  g 		monthlyTotalEnergyUsage solar energy transmittance of a building element
 *  Esol 	Solar irradiance                                            W/m2
 *  E 		Energy                                                      MJ
 *  H 		heat transfer coefficient W/K
 *  h 		surface coefficient of heat transfer                        W/(m²·K)
 *  L 		length                                                      m
 *  N 		number
 *  Q 		quantity of heat                                            MJ
 *  R 		thermal resistance                                          m²·K/W
 *  T 		thermodynamic temperature                                   K
 *  t 		time, period of time                                        Ms
 *  U 		thermal transmittance                                       W/(m²·K)
 *  V 		volume of air in a conditioned zone                         m³
 *  q 		airflow rate                                                m³/s
 *  Φ 		heat flow rate, thermal power W
 *  Ζ 		heat transfer parameter for solar walls                     W/(m²·K)
 *  α 		absorption coefficient of a surface for solar radiation
 *  γ 		Heat balance ratio
 *  ε 		emissivity of a surface for long-wave thermal radiation
 *  η 		efficiency, utilisation factor
 *  κ 		factor related to heat losses of ventilated solar walls
 *  θ 		Celsius temperature                                         °C
 *  ρ 		density                                                     kg/m³
 *  σ 		Stefan-Boltzmann constant (σ = 5,67 × 10-8 )                W/(m²·K4)
 *  τ 		time constant                                               h
 *  χ 		heat capacity per area                                      J/(m²·K)
 * ---------------------------------------------------------------------------------------
 *
 *  >>>> SUBSCRIPTS <<<<
 *  Symbol      Quantity Unit
 *  ----------- --------------------------------------------------------------------------
 *  C 			cooling, capacity, calculation, convective
 *  e 			exterior, envelope
 *  r 			radiative; recovered
 *  C,n 		cooling need, or building need for cooling
 *  i 			Internal (temperature)
 *  red 		reduced
 *  f 			frame
 *  gr 			ground
 *  H 			heating
 *  s 			supply (of air)
 *  H,n 		heating need, or building need for heating
 *  sh 			shading
 *  HC,n 		Heating and/or cooling need; building need for heating and/or cooling
 *  hol 		Holidays, long unoccupied period
 *  se 			surface external
 *  L 			Lighting (system)
 *  V 			Ventilation (system)
 *  si 			surface internal
 *  W 			hot water (system or need)
 *  Tot 		Total
 *  ss 			surface-sky average
 *  Th 			Thermal
 *  f 			form, final
 *  gn 			gains
 *  ls 			loss
 *  h 			hemispherical
 *  sys 		system
 *  tr 			Transmission (heat transfer)
 *  i,j,k,m,n 	dummy integers
 *  ve 			Ventilation (heat transfer)
 *  l 			layer
 *  int 		Internal (heat gains)
 *  ut 			utilised
 *  sol 		Solar (heat gains)
 *  O 			outdoor obstacles
 *  P 			related to power
 *  m 			metabolic, month, mass
 *  nut         Non-utilised
 *  mn 			mean
 *  u 			unconditioned
 *  a 			air an annual
 *  A 			appliances
 *  o 			overall
 *  w 			window
 *  aux 		auxiliary
 *  p 			partition wall
 *  y, z 		zone number
 *  bh 			boost heating
 *  pp 			peak power
 *  ⊥ 			perpendicular
 *  c 			structure
 *  ps 			permanent shading
 *  0 			baselineAnnualSummary; reference
 *  d 			design; daily, direct
 *  --------------------------------------------------------------------------------------
 */
`

**Comment by pjayathissa** [comment]
Thank you @wgayton for that information. I have modified the wiki and comments in the code accordingly
