### ISSUE TITLE
Changes required to analyze existing buildings

### ISSUE THREAD

**Issue by JustinZarb** [architecture-building-systems/RC_BuildingSimulator#18]
A more flexible geometry input is necessary for the Building class, to account for:
- non-rectangular floor plans
- rooms bounded by roofs in terms of transmission area and the resulting room volumes
- different windows bounding the same zone
- different wall constructions along the same zone
- bounding surfaces (wall and ground slab) below grade

The proposed changes include the following parameters:

window_area=4.0,
external_envelope_area=15.0,
room_depth=7.0,
room_width=5.0,
room_height=3.0,

U_walls=0.2,
U_windows=1.1,

I would create 4 objects: wall, window, roof, subgrade. The window object already exists for solar radiation calculations. Each object should have the following parameters:
- area
- u-value
- normal vector (optional, for solar analysis)

The heated floor area and volume would become attributes of the building object, which could be more aptly renamed to 'zone'

A further feature which may be added would be radiant properties, which would be useful particularly for roofs when calculating heating in summer.

**Comment by maxtillberg** [comment]
It would be useful to have the possibility to use calculated or messured solar radiation instead of a normal vector.

**Comment by JustinZarb** [comment]
I have addressed this, and modified radiation.py to compute direct and diffuse radiation from global horizontal radiation, which is more commonly available from weather stations. If you're interested, check out the _nested_rc_ branch, and let me know if you have any questions!
