### ISSUE TITLE
T_m fails to calculate

### ISSUE THREAD

**Issue by JustinZarb** [architecture-building-systems/RC_BuildingSimulator#21]
Probably something related to my use of the zone class nested in the Building class, but the unittest failed to pick it up. Requires the latest version of zone_sensor_compare.py (from Data-driven-building-retrofit) to replicate.

My first thought was that the bug  results from there being no solar gains, but I re-activated the windows in zone_sensor_compare and the problem persisted, so I'm still trying to figure it out.

**Comment by pjayathissa** [comment]
The input `solar_gains`takes only floats. In this example, an array was being inputed.
