### ISSUE TITLE
Discrepancy in the temperature adjustment factor

### ISSUE THREAD

**Issue by JustinZarb** [architecture-building-systems/RC_BuildingSimulator#23]
There seems to be a discrepancy between the equation for the temperature adjustment factor in the code and that written in building_physics.py on line 166, which is:

` b_ek = (1 - (ach_vent / (ach_tot)) * ventilation_efficiency)`

while ISO 13790 eq. 27 which it refers to is written as:
` b_ve,k =  1 - (ach_vent / ach_tot * ventilation_efficiency)`

It might also be a good idea to use the nomenclature in the code, and renaming b_ek to  b_ve,k

**Comment by pjayathissa** [comment]
Both equations you wrote above are identical. 
Just to prove it:

```
In [1]: ach_vent = 4.2

In [2]: ach_tot = 9.2

In [3]: ventilation_efficiency = 0.3

In [4]: (1 - (ach_vent / (ach_tot)) * ventilation_efficiency)
Out[4]: 0.8630434782608696

In [5]: 1 - (ach_vent / ach_tot * ventilation_efficiency)
Out[5]: 0.8630434782608696
```

Let me know if I have missed something, if not, you can close this issue

**Comment by JustinZarb** [comment]
Seems like you are right! I should have tested it this way before raising an issue, it was probably some other bug that made me think there was a problem here.
