### ISSUE TITLE
annualSimulation_importRadiation example is confusing to read

### ISSUE THREAD

**Issue by pjayathissa** [architecture-building-systems/RC_BuildingSimulator#27]
(1)
I went through the code and so far I haven't found any problems. I was confused by lines 92-95 in annualSimulation_importRadiation.py on my computer:

if hour == 3994:

        solar_gains = (dir_solar_gains + diffuse_solar_gains) * \
            Office.window_area * 0.7
but when I checked the same code on Github, it made sense:

    if hour == 3994:
        print dir_solar_gains + diffuse_solar_gains

    solar_gains = (dir_solar_gains + diffuse_solar_gains) * \
Office.window_area * 0.7

I double checked that my github was up to date, so I don't know what is causing this problem. While I understood the code, perhaps the solar equations in this example could be explained a little bit better in the wiki.

**Comment by JdPeppino** [comment]
The same issue confused me. The code does not have the 'print...' line, but the solar_gains equation indented. Running the code would only calculate total solar gains if hour == 3994.

**Comment by pjayathissa** [comment]
fixed with PR #46
