### ISSUE TITLE
RC_BuildingSimulator wiki errors

### ISSUE THREAD

**Issue by JdPeppino** [architecture-building-systems/RC_BuildingSimulator#30]
When going through the introductions and copying/adjusting the code, I experienced some errors, which I will enumerate here:

**10 min guide:**
- Zurich.calc_sun_position has the argument 'hoy', not 'HOY'
- Office.solve_building_energy has the argument't_out', not 'T_out'
- Furthermore, t_out has to be defined before (is missing)
   >> t_out = Zurich.weather_data['drybulb_C'][hour]

**Hourly Simulation:** (Issues also apply to Run Full Annual Simulation)
- Arguments in Building(args*) are not capitalised!
    - 'u_walls' and 'u_windows' instead of 'U_walls' and 'U_windows'
    - 'ach_vent' and 'ach_infl' instead of 'ACH_vent' and 'ACH_infl'
    - 't_set_heating' and 't_set_cooling' instead of 'T_set....'
    - When calling supply and emission systems, the called function is misspelled 4 times (capital letters 
      and missing underscore):
      As an example: 'supply_system' instead of 'supplySystem'

**Radiation Calculation:**
- Same issues with 'HOY'/'hoy'
- I am confused by the windows. When the azimuth angle of _south is 0_, and _east is 90_, why is west 
  180? Should not that be south, and 270 is west?
- 'T_m_prev' should be 't_m_prev'. Also 'T_m_next'

**Comment by pjayathissa** [comment]
Wiki Updated
