### ISSUE TITLE
Possibly refactor code to allow for non cube geometries

### ISSUE THREAD

**Issue by pjayathissa** [architecture-building-systems/RC_BuildingSimulator#32]
The current code only takes cube geometries.

Non-rectangular cubes could be considered with the following refactor

- Inputs: Change from height, width, length to floor area, total internal surface area,  external surface area, volume

**Comment by pjayathissa** [comment]
@JustinZarb: Your thoughts?

**Comment by JustinZarb** [comment]
I did something similar to what you're suggesting in the nested_rc branch.

Room volume and floor area remain attributes of the building object, but all the other parameters are defined by 'element' objects (see auxiliary>zone_builder.py), which are added to the zone. I am taking this further in the [Hive tool ](https://github.com/architecture-building-systems/hive/blob/eeeec5f9ea77bf4d77987054e236eaabc57ef64a/HIVE_RC_simulator/src/Hive_Hive.py#L723)
