### ISSUE TITLE
Occupancy_com.csv file?

### ISSUE THREAD

**Issue by JaeinKim85** [architecture-building-systems/RC_BuildingSimulator#4]
Hello. I am a student currently studying.
3R1C_Old_Simulator is not running.
The nested material does not include the Occupany_com.csv file.
If  I can not get it, I will try to make it.
Could you tell me what kind of data the material is?
I am really sorry you are busy.

**Comment by MauroLuzzatto** [comment]
if you write me your email address, I will send you the occupancy file. best, ML

**Comment by daren-thomas** [comment]
is the occupancy file data sensitive? can we open source it? or maybe just ship one with fake data?

**Comment by MauroLuzzatto** [comment]
I added the occupancy file to the data folder.

**Comment by JaeinKim85** [comment]
Thank you. I received occupancy file.  thank you ur kindness.

2017-01-10 17:28 GMT+09:00 MauroLuzzatto <notifications@github.com>:
