### ISSUE TITLE
Is it possible to define more than one wall and window?

### ISSUE THREAD

**Issue by cheak1974** [architecture-building-systems/RC_BuildingSimulator#42]
Hi,

very nice library. If I understand the workflow right the building object is more meant to be a room, right? So if I want to run a simulation with multiple rooms with different justification of the windows then  I have to create more than one building.

Would it not be more straight to define a building object, hook in multiple rooms into a dict?

With this question one more came up. Is it possible for a room to define more than one outer surface (wall). Maybe you have a basement or roof room with a wall and a roof which could have different U values. Also here I expected to have a dict with the walls. Same with the windows. A room on the corner of a building could have windows to two different directions. Also here a dict with the windows per room would be logical (maybe with the direction, azimuth, U-value and factors?).

If you would define the building like that you could run a simulation automatically over a location and calculate radiation and illuminance  for the windows automatically.

Just dreaming :-)

regards

Chris

**Comment by pjayathissa** [comment]
Hi Cheak, thanks for the issue request. This is related to Issue #26 and #32 . Which involves changing the syntax from `building` to `zone`

When it comes to multiple outer walls, I take an average U-value of the system and plug that into the equation. This can be pre-calculated based on the surface area and respective u-values. If your outside environment has a different outside temperature then you need to factor this temperature variation to create an effective u-value. I remember @JustinZarb attempting to solve this issue so he may have a better answer. That way the model doesn't need to increase in complexity, but you just do some custom pre-calc, and it will still mathematically come to the same answer.

Now, your issue with different rooms is possible, if there is no inter-relationship between the rooms. For example if we assume the thermal transfer between rooms is negligible (which is fair if they are equally conditioned), then there is no problem as we can maintain the assumption of adiabatic surfaces to adjacent rooms. You can then build an actual building with multiple zones in a dictionary as you mentioned and iterate through them.

But if you did have heat transfer between zones then everything becomes more complicated as you would need to build the inter-relationship between the zones, which would require a significant increase in computational power to find the point where the multiple zones come into their convergence point. This is what I tried to avoid as I was going for speed over complexity in the development of this algorithm.

Your windows question is a good one which comes in Issue #33 . Currently windows is defined in two separate areas. One for a u-value calculation and again as a radiation calculation `Radiation.py`. In the radiation code, you can define multiple windows, of varying angles. Just be careful to make sure that the overall surface area matches for the u-value calculation which exists in the base BuildingPhysics.py. Check out https://github.com/architecture-building-systems/RC_BuildingSimulator/blob/master/rc_simulator/examples/annualSimulation.py

Hope this helps

**Comment by pjayathissa** [comment]
Solved with PR #46 and PR #44 

Also added an example file of how multiple walls can be defined `examples/multiWall.py`
