### ISSUE TITLE
Python 3 compatible

### ISSUE THREAD

**Issue by lukas-rokka** [architecture-building-systems/RC_BuildingSimulator#5]
Just tested the example files and noticed that its written for python 2. 

Now I'm not experienced in Python, but there was just a few changes required to get the two examples and the test running with Python 3: adding parentheses to all print statements; removing the b from `with open(epw_name, 'rb') as csvfile:` to `with open(epw_name, 'r') as csvfile:`.

**Comment by pjayathissa** [comment]
Hi Lukas

This is something that I plan on doing when I refactor the code for deployment. For now is it possible for you to run python2 in your software?

**Comment by lukas-rokka** [comment]
Sure, just wanted to notify that it was quite small things that needed changes for making it python 3 compatible.
