### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by lukas-rokka** [architecture-building-systems/RC_BuildingSimulator#6]
First off, thanks for sharing your work!

I'm interesting to implement the 5R1C method into my project at https://rokka.shinyapps.io/smartep

What is your intentions with the project? Any roadmap of the development the nearest time?

**Comment by pjayathissa** [comment]
Hi Lukas

I'm sorry for the late reply. Somehow my notifications were turned off. 

So, the building model is functional, and is already being used in some of our projects. We are in the process of developing some additional functionality such as a rapid solar radiation model, and the integration of building systems. 

If you let me know what functionality you need, I would be happy to assist you in the implementation of this to your project

**Comment by lukas-rokka** [comment]
Thanks, right now just looking for whats available in form of simple resistance-capacitance models suitable for grey-box modelling. I let you know if we start using this repository seriously (would be in the autumn)

**Comment by pjayathissa** [comment]
Autumn (northern hemisphere) works well. In the next month I plan on merging some branches and producing the documentation for the use of this tool
