### ISSUE TITLE
COPs of heat pumps are still allowed to go unrealistically high.

### ISSUE THREAD

**Issue by Mifehr** [architecture-building-systems/RC_BuildingSimulator#7]
Heat pumps (supplySystems.py) should get an additional if statement to limit their COPs (special importance for cooling).

**Comment by pjayathissa** [comment]
Equations changed based on
OP based off regression anlysis of manufacturers data
    Source: "A review of domestic heat pumps, Iain Staffell, Dan Brett, Nigel Brandonc and Adam Hawkes"
    http://pubs.rsc.org/en/content/articlepdf/2012/ee/c2ee22653g
